server {
    listen 80;
    listen [::]:80;
    server_name ospro.pt;
    root /var/www/html;
    index index index.php;
     return 302 https://$host:443/;
    location ~ /.well-known/acme-challenge {
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_pass http://127.0.0.1:9180;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ospro.pt;
    root /var/www/html;
    index index index.php;
    ssl_certificate /etc/nginx/ssl/ospro.pt_P256/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/ospro.pt_P256/private.key;
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
    }
    # Nginx php-cgi config :
    # Nginx PHP fastcgi_pass 127.0.0.1:9000;
    location ~ /\.ht {
        deny all;
    }
    location / {
        try_files $uri $uri/ =404;
    }
    location ~ /.well-known/acme-challenge {
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_pass http://127.0.0.1:9180;
    }
}